; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = arduino, espidf
monitor_speed = 115200
upload_port = /dev/ttyUSB1
upload_protocol = esptool
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.sdkconfig_defaults = sdkconfig.defaults
board_build.partitions = default.csv
extra_scripts =
	pre:scripts/ota_custom_signing.py
build_flags =
	-D OTA_UPLOAD_PASSWORD=\"\"
lib_deps =
	rweather/Crypto

[env:az-delivery-devkit-v4-ota]
extends = env:az-delivery-devkit-v4
upload_protocol = espota
upload_port = 192.168.44.172
upload_flags =
	--port=3232
	--host_port=3233
	--host_ip=192.168.44.1